# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentsec.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agentsec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61gentsec.proto\x12\x0b\x61gentsec.v1\"=\n\x0f\x45valuateRequest\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12\x12\n\nevent_json\x18\x02 \x01(\t\"A\n\x10\x45valuateResponse\x12\x16\n\x0eschema_version\x18\x01 \x01(\x05\x12\x15\n\rdecision_json\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\"8\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0eschema_version\x18\x02 \x01(\x05\x32\x97\x01\n\tGuardrail\x12G\n\x08\x45valuate\x12\x1c.agentsec.v1.EvaluateRequest\x1a\x1d.agentsec.v1.EvaluateResponse\x12\x41\n\x06Health\x12\x1a.agentsec.v1.HealthRequest\x1a\x1b.agentsec.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentsec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATEREQUEST']._serialized_start=31
  _globals['_EVALUATEREQUEST']._serialized_end=92
  _globals['_EVALUATERESPONSE']._serialized_start=94
  _globals['_EVALUATERESPONSE']._serialized_end=159
  _globals['_HEALTHREQUEST']._serialized_start=161
  _globals['_HEALTHREQUEST']._serialized_end=176
  _globals['_HEALTHRESPONSE']._serialized_start=178
  _globals['_HEALTHRESPONSE']._serialized_end=234
  _globals['_GUARDRAIL']._serialized_start=237
  _globals['_GUARDRAIL']._serialized_end=388
# @@protoc_insertion_point(module_scope)
