# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agentsec_pb2 as agentsec__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentsec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuardrailStub:
    """Guardrail decision service (PDP). The event/decision payloads are carried as
    JSON strings so the gRPC surface reuses the exact same wire contract as the
    HTTP transport (AgentEvent.to_dict() / Decision.to_dict()) — one source of
    truth, no parallel schema to maintain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/agentsec.v1.Guardrail/Evaluate',
                request_serializer=agentsec__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=agentsec__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agentsec.v1.Guardrail/Health',
                request_serializer=agentsec__pb2.HealthRequest.SerializeToString,
                response_deserializer=agentsec__pb2.HealthResponse.FromString,
                _registered_method=True)


class GuardrailServicer:
    """Guardrail decision service (PDP). The event/decision payloads are carried as
    JSON strings so the gRPC surface reuses the exact same wire contract as the
    HTTP transport (AgentEvent.to_dict() / Decision.to_dict()) — one source of
    truth, no parallel schema to maintain.
    """

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuardrailServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=agentsec__pb2.EvaluateRequest.FromString,
                    response_serializer=agentsec__pb2.EvaluateResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agentsec__pb2.HealthRequest.FromString,
                    response_serializer=agentsec__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentsec.v1.Guardrail', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentsec.v1.Guardrail', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Guardrail:
    """Guardrail decision service (PDP). The event/decision payloads are carried as
    JSON strings so the gRPC surface reuses the exact same wire contract as the
    HTTP transport (AgentEvent.to_dict() / Decision.to_dict()) — one source of
    truth, no parallel schema to maintain.
    """

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentsec.v1.Guardrail/Evaluate',
            agentsec__pb2.EvaluateRequest.SerializeToString,
            agentsec__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentsec.v1.Guardrail/Health',
            agentsec__pb2.HealthRequest.SerializeToString,
            agentsec__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
